[flow]
name = "Increment counter subflow"

[flow.options]
app_lifecycle = "manual"

[[block]]
name = "increment"
steps = [
  { action = "tap", text = "Increment" },
  { action = "read", below = "Counter", element_type = "text", save_to = "counter_value" },
]
